Shopping basket billing
akavinash1994/ruby_training pull request #4
Opened 2017-07-05 14:27 UTC by akavinash1994

2017-07-07 12:45 UTC, asharma-ror commented on code/item.rb
> +  end
@akavinash1994  in billing you find item name by `(item.imported? ? ' imported ' : ' ') + item.display_name  `
Could you update `def display_name` 
so it append `impoted` in display name if item is imported

2017-07-07 12:56 UTC, rahul-mishra-ror requested changes

2017-07-07 12:56 UTC, rahul-mishra-ror commented on code/order.rb
> +    output << 'Sales Taxes : ' + total_tax.to_s
@akavinash1994 Can we include below statement in `display_name` ?
 `item.imported? ? ' imported '  :  ' '  +  item.display_name`

2017-07-11 04:16 UTC, rahul-mishra-ror approved these changes
:boom:

2017-07-11 04:16 UTC, merged